name: "analytics_engineering_template"

config-version: 2
version: "1.0.0"

profile: "analytics_engineering_template"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: ">=1.9.0"

models:
  analytics_engineering_template:
    marts:
      +materialized: table
      +schema: core
    staging:
      +materialized: view
      +schema: staging
  dbt_project_evaluator:
    +materialized: table
    +schema: eval

seeds:
  analytics_engineering_template:
    dbt_project_evaluator_exceptions:
      +schema: eval
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

vars:
  "dbt_date:time_zone": "UTC"

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']
